### ISSUE TITLE
Disallow bot settings to be changed by group members

### ISSUE THREAD

**Issue by Daksh777** [nminaya/grammar-nazi-bot#1]
The members of a group can change the bot settings like algorithm, language, etc. and can spam the commands while also ruining other people's corrections by changing the language. It would be good if the settings in groups could only be changed by the group admins.

**Comment by nminaya** [comment]
@Daksh777 Now the bot will only execute some commands if the user is administrator

**Comment by Daksh777** [comment]
Amazing!
