### ISSUE TITLE
Exclude emojis from being checked

### ISSUE THREAD

**Issue by Daksh777** [nminaya/grammar-nazi-bot#117]
![image](https://user-images.githubusercontent.com/43648146/106588599-fe2c7100-6570-11eb-87a7-77720495d448.png)

**Comment by nminaya** [comment]
I was able to reproduce the issue, only happens with YandexSpellerAPI. We currently exclude emojis in the following line:

https://github.com/nminaya/grammar-nazi-bot/blob/1058b5a991e251aac63393bfe06e355bdaadca3d/GrammarNazi.App/HostedServices/TelegramBotHostedService.cs#L126-L127

But something interesting is happening. 

1. ```GetCleanedText("bored")``` returns "bored".
2. ```GetCleanedText("bored🔫😡😆😡❤️😡😡❤️")``` returns "bored".

They're apparently the same, but when this text is parsed with HttpUtility.UrlEncode in 
https://github.com/nminaya/grammar-nazi-bot/blob/1058b5a991e251aac63393bfe06e355bdaadca3d/GrammarNazi.Core/Clients/YandexSpellerApiClient.cs#L30

```HttpUtility.UrlEncode("bored")``` is returning "bored%ef%b8%8f%ef%b8%8f", and this is causing the API to return a correction for this word.

I need to verify how to clean the text of these invisible characters in ```GetCleanedText``` or ```StringUtils.RemoveEmojis``` method.
