### ISSUE TITLE
Create new Twitter account

### ISSUE THREAD

**Issue by nminaya** [nminaya/grammar-nazi-bot#136]
So after a month waiting, Twitter finally sent a response. Unfortunately Twitter will not restore the account. #76
![image](https://user-images.githubusercontent.com/7952888/108997343-dca53d80-7675-11eb-8f1f-1de87836b048.png)

So we will be creating a new Twitter account.

If you're curious about what was the "hateful" content in my profile, here is: https://s3.amazonaws.com/colorslive/jpg_512x512/795676-jY8zhAS-LPAwWVTn.jpg

**Comment by Jadhielv** [comment]
Why is it still open? @nminaya

**Comment by nminaya** [comment]
@Jadhielv I think it should be closed too xd
