### ISSUE TITLE
Command handling improvement for Telegram Bot

### ISSUE THREAD

**Issue by nminaya** [nminaya/grammar-nazi-bot#145]
## Command Handling Improvement
Instead of having a lot of ```if else``` for each command in [TelegramCommandHandlerService](https://github.com/nminaya/grammar-nazi-bot/blob/53b2c690ff6c09c25edc18ba61e0b7dd07ce9473/GrammarNazi.Core/Services/TelegramCommandHandlerService.cs#L28), create a ITelegramBotCommand interface (similar to [IDiscordBotCommand](https://github.com/nminaya/grammar-nazi-bot/blob/master/GrammarNazi.Domain/BotCommands/IDiscordBotCommand.cs)) and create a class that implement this interface for each command.

### Follow the pattern of Discord Bot command handling.
- Create a BaseTelegramCommand for the common methods used by each command (similar to [BaseDiscordCommand](https://github.com/nminaya/grammar-nazi-bot/blob/master/GrammarNazi.Core/BotCommands/Discord/BaseDiscordCommand.cs)).
- Migrate and adapt the unit tests in [TelegramCommandHandlerServiceTests](https://github.com/nminaya/grammar-nazi-bot/blob/master/GrammarNazi.Tests/Services/TelegramCommandHandlerServiceTests.cs).
- Create an extension for IServiceCollection that registers all ITelegramBotCommand commands of the current Assembly (similar to [AddDiscordBotCommands](https://github.com/nminaya/grammar-nazi-bot/blob/53b2c690ff6c09c25edc18ba61e0b7dd07ce9473/GrammarNazi.Core/Extensions/ServiceCollectionExtensions.cs#L32) extension).
- Remove the if else's in [TelegramCommandHandlerService.Handle](https://github.com/nminaya/grammar-nazi-bot/blob/53b2c690ff6c09c25edc18ba61e0b7dd07ce9473/GrammarNazi.Core/Services/TelegramCommandHandlerService.cs#L28) and all other unused methods and dependencies.

**Comment by Jadhielv** [comment]
I would like to help you with this @nminaya

**Comment by nminaya** [comment]
@Jadhielv Go ahead, this issue involves a lot of changes. Any difficulties you can reach out to me.
