### ISSUE TITLE
Move telegram bot command handler logic

### ISSUE THREAD

**Issue by nminaya** [nminaya/grammar-nazi-bot#16]
We need to move into a separate class all the logic inside TelegramBotHostedService.HandleCommand method, so that it will be easier to test.
https://github.com/nminaya/grammar-nazi-bot/blob/d84df8519226ad899d8bb58a070bedf79876438a/GrammarNazi.App/HostedServices/TelegramBotHostedService.cs#L144

Create a **ITelegramCommandHandler** with the following signature:
```cs
Task HandleCommand(ITelegramBotClient client, Message message);
```
The implementation of this method should be the same as in TelegramBotHostedService.HandleCommand.

After the creation of the implementation of this new ITelegramCommandHandler, the TelegramBotHostedService.HandleCommand method should be removed and use the ITelegramCommandHandler.HandleCommand instead.

**Comment by Jadhielv** [comment]
I would like to help you with this @nminaya

**Comment by nminaya** [comment]
@Jadhielv Sure, go ahead!
