### ISSUE TITLE
Repeated word in Whitelist

### ISSUE THREAD

**Issue by nminaya** [nminaya/grammar-nazi-bot#163]
Currently you can whitelist the same word in a different combination of uppercase and lowercase.

![image](https://user-images.githubusercontent.com/7952888/111562968-7c358780-876d-11eb-84a2-0576d3049954.png)

Make case insensitive the following validations:
https://github.com/nminaya/grammar-nazi-bot/blob/96171067ed59949104f89468b7dfdd8b4da3656b/GrammarNazi.Core/BotCommands/Discord/AddWhiteListCommand.cs#L41
https://github.com/nminaya/grammar-nazi-bot/blob/96171067ed59949104f89468b7dfdd8b4da3656b/GrammarNazi.Core/Services/TelegramCommandHandlerService.cs#L331

**Comment by nminaya** [comment]
The case insensitive validation is also needed for ```remove_whitelist``` command

**Comment by Jadhielv** [comment]
Why is it still open? @nminaya

**Comment by nminaya** [comment]
@Jadhielv Because the bug is still present in the Telegram bot. The PR #164 was the fix just for the Discord Bot.

I can work on the fix for the Telegram Bot, but that could cause conflicts with the work you're doing for #145

**Comment by Jadhielv** [comment]
#145 closed. Now you can continue @nminaya
