### ISSUE TITLE
Create value comparer for WhiteListWords property

### ISSUE THREAD

**Issue by nminaya** [nminaya/grammar-nazi-bot#206]
Create a ValueComparer for the mapping configurations of WhiteListWords properties in:

https://github.com/nminaya/grammar-nazi-bot/blob/5d864e0a233838587d0371fe92d580769284f61b/GrammarNazi.Core/GrammarNaziContext.cs#L30-L36

So that we remove the following warnings:

![image](https://user-images.githubusercontent.com/7952888/116173669-fcd79400-a6da-11eb-8d46-eae6e92a5519.png)

**Comment by Jadhielv** [comment]
I would like to help you with this @nminaya
