### ISSUE TITLE
Use Telegram.Bot Polling

### ISSUE THREAD

**Issue by nminaya** [nminaya/grammar-nazi-bot#259]
The last version of Telegram.Bot marked the methods and events we use to receive messages as Obsolete/Deprecated.

They recommend to use Polling: https://github.com/TelegramBots/Telegram.Bot.Examples/blob/master/Telegram.Bot.Examples.Polling/Program.cs

**Comment by Jadhielv** [comment]
I would like to help you with this @nminaya

**Comment by nminaya** [comment]
@Jadhielv Ok, go ahead

**Comment by nminaya** [comment]
@Jadhielv This will need some testing as well
