### ISSUE TITLE
Update to .NET 5

### ISSUE THREAD

**Issue by nminaya** [nminaya/grammar-nazi-bot#31]
Upgrade from .NET Core 3.1 to .NET 5.

Change the target framework of all projects.

```xml
<TargetFramework>net5.0</TargetFramework>
```

Update the Dockerfile with the new docker images:

- mcr.microsoft.com/dotnet/aspnet:5.0
- mcr.microsoft.com/dotnet/sdk:5.0

**Comment by Jadhielv** [comment]
I would like to help you with this @nminaya

**Comment by nminaya** [comment]
@Jadhielv Sure, Go ahead!
