### ISSUE TITLE
Update to .NET 6

### ISSUE THREAD

**Issue by Jadhielv** [nminaya/grammar-nazi-bot#323]
Upgrade from .NET Core 5.0 to .NET 6.

Change the target framework of all projects.

```xml
<TargetFramework>net6.0</TargetFramework>
```

Update the Dockerfile with the new docker images:

- mcr.microsoft.com/dotnet/aspnet:6.0
- mcr.microsoft.com/dotnet/sdk:6.0

**Comment by nminaya** [comment]
I was about to create this issue since the official NET 6 was released today, but you're going ahead xd 👍
