### ISSUE TITLE
Whitelist or ignore words

### ISSUE THREAD

**Issue by Daksh777** [nminaya/grammar-nazi-bot#39]
It would be great if it were possible to whitelist or ignore some specific words per group. For example, a person's name gets corrected, so it would be great if it could be ignored as a message to be checked with the API.

**Comment by nminaya** [comment]
@Daksh777 Thanks for the suggestion, it's a great idea. I think that for the current Grammar Algorithms, the names should start with a capital letter to be recognized as a name. But anyway I'll be working on a Whitelist Words feature 👍🏼

**Comment by Daksh777** [comment]
> @Daksh777 Thanks for the suggestion, it's a great idea. I think that for the current Grammar Algorithms, the names should start with a capital letter to be recognized as a name. But anyway I'll be working on a Whitelist Words feature 👍🏼

You are correct, this is more of a problem with the Yandex Speller API actually
![image](https://user-images.githubusercontent.com/43648146/100519915-ef1bf200-31c0-11eb-8ea2-e7e5d7aa1294.png)
