### ISSUE TITLE
Telegram bot is analyzing fowarded messages

### ISSUE THREAD

**Issue by nminaya** [nminaya/grammar-nazi-bot#41]
The Telegram bot shouldn't analyze fowarded messages.

Use ```message.ForwardDate``` to validate.

**Comment by nminaya** [comment]
Thinking it better, this bug may be more of a feature 🤔

**Comment by Daksh777** [comment]
> Thinking it better, this bug may be more of a feature 🤔

How about adding an option to toggle text analysis for forwarded messages? Some groups have channels linked to them, so the owners can check if there are any problems with it.

**Comment by nminaya** [comment]
@Daksh777 I discarded this bug. The Telegram Bot is currently analyzing any message posted in the Chat
