### ISSUE TITLE
Bot is correcting mentions for people with no usernames

### ISSUE THREAD

**Issue by Daksh777** [nminaya/grammar-nazi-bot#5]
![image](https://user-images.githubusercontent.com/43648146/95414470-96ac3f00-094b-11eb-8e13-96fa248d9409.png)

**Comment by nminaya** [comment]
@Daksh777 Hi, thanks for reporting the issue.

I have pushed a fix for this bug. Please try again and let me know 👍🏼

**Comment by Daksh777** [comment]
Hey @nminaya,
Thanks a lot! The bug seems to be fixed, I'll close this issue.
