### ISSUE TITLE
Switch from Moq to NSubstitute due to the controversy of version 4.20

### ISSUE THREAD

**Issue by Jadhielv** [nminaya/grammar-nazi-bot#619]
I'm considering switching from Moq to NSubstitute due to the controversy of version 4.20

_Originally posted by @nminaya in https://github.com/nminaya/grammar-nazi-bot/issues/617#issuecomment-1677632586_

**Comment by nminaya** [comment]
This article was really useful for the migration [https://itnext.io/how-to-migrate-from-moq-to-nsubstitute-cdb6a80404d](https://itnext.io/how-to-migrate-from-moq-to-nsubstitute-cdb6a80404d )
