### ISSUE TITLE
Twitter Bot - Publish corrections in several tweets when max characters exceeded

### ISSUE THREAD

**Issue by nminaya** [nminaya/grammar-nazi-bot#73]
When the Twitter Bot corrects a Tweet with several grammar errors, the list of correctios makes the tweet to publish exceeds the max character length allowed by Twitter.

When this happen, the Bot should separate the corrections in various tweets.

**Comment by Jadhielv** [comment]
I would like to help you with this @nminaya

**Comment by nminaya** [comment]
@Jadhielv Sure 👌🏼
